[package]
name = "process_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
wmi = "0.14"
chrono = "0.4"
serde = "1.0"
egui = "0.29.0"
eframe = "0.29"

[profile.shipping]
inherits = "release"
lto = "fat"
debug = false
codegen-units = 1
strip = "symbols"
panic = "abort"