name: Increment Tag on Push

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  increment-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag, default to v0.0.0 if no tags exist
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "::set-output name=LATEST_TAG::$latest_tag"

      - name: Increment tag version
        id: increment_tag
        run: |
          # Remove the 'v' from the version tag (e.g., v1.0.0 -> 1.0.0)
          latest_tag="${{ steps.get_tag.outputs.LATEST_TAG }}"
          version="${latest_tag#v}"
          
          # Split the version into its components
          IFS='.' read -r major minor patch <<< "$version"

          # Increment the patch version
          new_patch=$((patch + 1))

          # Form the new tag
          new_tag="v$major.$minor.$new_patch"
          echo "New tag: $new_tag"
          echo "::set-output name=NEW_TAG::$new_tag"

      - name: Create new tag
        run: |
          git tag ${{ steps.increment_tag.outputs.NEW_TAG }}
          git push origin ${{ steps.increment_tag.outputs.NEW_TAG }}
